"""Bridge Gazebo topics into the /duburi/sim namespace that duburi_ws expects.

Deliberately small. All vehicle control reaches ArduSub over MAVLink on UDP
14550, not across this bridge, so the only things that have to cross are camera
images, their calibration, ground truth and the clock.

Also launches underwater_fx, which publishes image_fx alongside the raw
contract topics (raw topics stay untouched).
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

FRONT_IMAGE = '/duburi/sim/front_camera/image_raw'
BOTTOM_IMAGE = '/duburi/sim/bottom_camera/image_raw'
FRONT_INFO = '/duburi/sim/front_camera/camera_info'
BOTTOM_INFO = '/duburi/sim/bottom_camera/camera_info'
GROUND_TRUTH = '/duburi/sim/ground_truth'
FRONT_BOXES = '/duburi/sim/front_camera/boxes'
BOTTOM_BOXES = '/duburi/sim/bottom_camera/boxes'


def _underwater_fx(context, fx_defaults):
    """The underwater_fx node, with the per-course turbidity file layered on.

    An OpaqueFunction because `fx_params` can only be checked for existence
    after substitutions resolve. A course generated by gen_world.py always has
    its sidecar; a hand-written .world dropped in by an operator does not, and
    a missing parameter file is a hard launch failure rather than a warning --
    so the file is dropped when it is not there and the defaults stand alone.
    """
    layered = [fx_defaults]
    per_course = LaunchConfiguration('fx_params').perform(context)
    if per_course and os.path.isfile(per_course):
        layered.append(per_course)
    return [Node(
        package='duburi_sim_bridge',
        executable='underwater_fx',
        name='underwater_fx',
        parameters=layered,
        output='screen',
    )]


def generate_launch_description():
    vehicle_name = LaunchConfiguration('vehicle_name')
    fx = LaunchConfiguration('fx')

    odom_gz_topic = ['/model/', vehicle_name, '/odometry']
    odom_spec = odom_gz_topic + ['@nav_msgs/msg/Odometry[gz.msgs.Odometry']

    # Turbidity. The course's <course>.fx.yaml (written by gen_world.py from the
    # `lighting:` preset) is layered OVER the package default, so a course that
    # names a preset gets its water and one that does not still gets sane values.
    # This is the real turbidity path: gz-sim 8 ignores the world's <scene><fog>
    # entirely -- measured -- so the preset would otherwise be decorative.
    fx_defaults = os.path.join(
        get_package_share_directory('duburi_sim_bridge'),
        'config',
        'underwater_fx.yaml',
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            'vehicle_name',
            default_value='duburi',
            description='Vehicle instance name, as set by the course YAML.',
        ),
        DeclareLaunchArgument(
            'fx',
            default_value='true',
            description='Launch underwater_fx (image_fx topics).',
        ),
        DeclareLaunchArgument(
            'fx_params',
            default_value='',
            description='Per-course turbidity YAML (<course>.fx.yaml). '
                        'Empty = package defaults only.',
        ),

        Node(
            package='ros_gz_image',
            executable='image_bridge',
            name='duburi_sim_image_bridge',
            # Range images are bridged too. When configs.yaml leaves
            # `range_cameras: false` the sensors are stripped from the model
            # and these two simply never carry anything -- image_bridge
            # advertises the topic either way, which is why `gz topic -l` still
            # lists them. Harmless, but do not read their presence as evidence
            # the sensors are running.
            arguments=['/front_camera', '/bottom_camera',
                       '/front_range', '/bottom_range'],
            remappings=[
                ('/front_camera', FRONT_IMAGE),
                ('/bottom_camera', BOTTOM_IMAGE),
                ('/front_range', '/duburi/sim/front_camera/range'),
                ('/bottom_range', '/duburi/sim/bottom_camera/range'),
            ],
            output='screen',
        ),

        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='duburi_sim_bridge',
            arguments=[
                '/front_camera/camera_info@sensor_msgs/msg/CameraInfo['
                'gz.msgs.CameraInfo',
                '/bottom_camera/camera_info@sensor_msgs/msg/CameraInfo['
                'gz.msgs.CameraInfo',
                odom_spec,
                '/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock',
                # Ground-truth 2D boxes for dataset labelling. ros_gz_bridge
                # ships this conversion compiled in (Detection2DArray <-
                # gz.msgs.AnnotatedAxisAligned2DBox_V), unlike the DVL below
                # which has none and needs a node of its own.
                '/front_boxes@vision_msgs/msg/Detection2DArray['
                'gz.msgs.AnnotatedAxisAligned2DBox_V',
                '/bottom_boxes@vision_msgs/msg/Detection2DArray['
                'gz.msgs.AnnotatedAxisAligned2DBox_V',
            ],
            remappings=[
                ('/front_camera/camera_info', FRONT_INFO),
                ('/bottom_camera/camera_info', BOTTOM_INFO),
                (odom_gz_topic, GROUND_TRUTH),
                ('/front_boxes', FRONT_BOXES),
                ('/bottom_boxes', BOTTOM_BOXES),
            ],
            output='screen',
        ),

        OpaqueFunction(
            function=_underwater_fx, args=[fx_defaults],
            condition=IfCondition(fx),
        ),
        # DVL. NOT a parameter_bridge entry: ros_gz_bridge has no
        # gz.msgs.DVLVelocityTracking conversion and ros_gz_interfaces has no
        # matching .msg, so this speaks gz-transport directly.
        #
        # Observability only. The control path (duburi_sensors' SimDvlSource)
        # subscribes to the gz topic itself, so the *_dist verbs keep working
        # even if this node is down -- deliberately, so a debugging tool can
        # never be load-bearing for vehicle control.
        Node(
            package='duburi_sim_bridge',
            executable='dvl_bridge',
            name='duburi_sim_dvl_bridge',
            output='screen',
        ),
    ])
