#!/usr/bin/env python3
"""Emit the RViz URDF from the SAME config the Gazebo SDF is generated from.

Gazebo consumes SDF; RViz's RobotModel display can only read URDF. Keeping two
hand-written descriptions of one vehicle is how they drift, and a drifted URDF
is worse than none: RViz would draw a robot that is confidently wrong about
where its cameras are, which is precisely the class of "believed vs true" error
this simulator exists to expose.

So this reuses `generate_model.get_model_params_from_config` -- the identical
`ModelParams` object that fills `model.sdf.in`. Camera and DVL offsets can only
be wrong in both files at once, never in one.

Scope is deliberately small: the visual hull, the sensor frames RViz needs, and
`odom`. Thrusters are NOT emitted -- they are revolute joints whose angles
nothing publishes, so `robot_state_publisher` would either demand a
`/joint_states` stream that does not exist or peg them all at zero. An eight-way
lie about propeller position is not worth the mesh.

    scripts/generate_urdf.py <config.yaml> <out.urdf>
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate_model import get_model_params_from_config  # noqa: E402

MESH_PKG = 'package://duburi_sim_description/models/duburi_heavy/meshes'

TEMPLATE = """<?xml version="1.0"?>
<!-- GENERATED by duburi_sim_description/scripts/generate_urdf.py
     from models/duburi_heavy/configs.yaml, the same source as model.sdf.
     Do not hand-edit: run the generator. -->
<robot name="{name}">

  <!-- base_link is the ROOT. `odom` is deliberately NOT a link here: it is
       supplied at runtime as a dynamic odom to base_link transform by
       duburi_sim_bridge's ground-truth broadcaster. Declaring it in the URDF
       would need a floating joint, which robot_state_publisher ignores, so the
       link would exist in the model and never in TF. -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{mesh_pkg}/duburi_heavy.dae"/>
      </geometry>
    </visual>
  </link>

  <!-- Sensor frames. Offsets come from configs.yaml, so they cannot disagree
       with the Gazebo model. -->
  <link name="front_camera_link"/>
  <joint name="front_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_camera_link"/>
    <origin xyz="{fcx} {fcy} {fcz}" rpy="0 0 0"/>
  </joint>

  <link name="bottom_camera_link"/>
  <joint name="bottom_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_camera_link"/>
    <origin xyz="{bcx} {bcy} {bcz}" rpy="0 -1.5707963 0"/>
  </joint>

  <!-- The DVL sensor itself sits on base_link in the SDF (on its own link it
       read ~0 velocity). This frame is for display only: it marks where the
       array is mounted and which way it looks. -->
  <link name="dvl_link"/>
  <joint name="dvl_joint" type="fixed">
    <parent link="base_link"/>
    <child link="dvl_link"/>
    <origin xyz="{dvx} {dvy} {dvz}" rpy="3.1415927 0 0"/>
  </joint>

{gripper}
</robot>
"""

# Emitted only when configs.yaml enables the gripper, so the URDF and the SDF
# describe the same vehicle. RViz would otherwise show a hull with no arm while
# Gazebo simulated one -- the exact SDF/URDF divergence the drift guard exists
# to prevent, just in the other direction.
GRIPPER = """
  <!-- Newton-shaped gripper. The jaws are revolute in the SDF; here they are
       FIXED at the closed position, for the same reason the thrusters are not
       emitted at all: nothing publishes /joint_states for them, so
       robot_state_publisher would either demand a stream that does not exist or
       peg them at zero. A closed jaw is the honest still pose. -->
  <link name="gripper_body_link"/>
  <joint name="gripper_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gripper_body_link"/>
    <origin xyz="{gx} {gy} {gz}" rpy="0 1.5707963 0"/>
  </joint>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('config')
    ap.add_argument('outfile')
    args = ap.parse_args()

    p = get_model_params_from_config(args.config)
    urdf = TEMPLATE.format(
        name=p.model_name_plain,
        mesh_pkg=MESH_PKG,
        fcx=p.front_camera_x, fcy=p.front_camera_y, fcz=p.front_camera_z,
        bcx=p.bottom_camera_x, bcy=p.bottom_camera_y, bcz=p.bottom_camera_z,
        dvx=p.dvl_x, dvy=p.dvl_y, dvz=p.dvl_z,
        gripper=(GRIPPER.format(gx=p.gripper_x, gy=p.gripper_y,
                                gz=p.gripper_z) if p.gripper_on else ''),
    )
    # `--` is illegal inside an XML comment and every parser rejects the file.
    # Caught here rather than at load time, because a URDF that fails to parse
    # shows up in RViz as a silently absent robot, not an error.
    for c in re.findall(r'<!--.*?-->', urdf, re.S):
        if '--' in c[4:-3]:
            raise SystemExit(f'illegal "--" inside an XML comment:\n{c[:120]}')

    with open(args.outfile, 'w') as fh:
        fh.write(urdf)
    print(f'wrote {args.outfile}')


if __name__ == '__main__':
    main()
