"""Make `import duburi_*` resolve to THIS checkout. Always. Everywhere.

⛔ THE PROBLEM THIS EXISTS TO KILL, because it has now cost several rounds.

Sourcing a colcon workspace puts its `install/` tree on `PYTHONPATH`:

    PYTHONPATH=/…/duburi_ws/install/duburi_vision/lib/python3.10/site-packages
               /…/duburi_ws/install/duburi_manager/lib/python3.10/site-packages
               …

`import duburi_vision` then resolves THERE, not to the source beside the test.
Three ways that bites, all of them silent:

  * IN A WORKTREE -- a second checkout (a branch under review, this one) has
    its own `src/` and NO install tree, so every test imports the OTHER
    workspace's build. Round 34 spent a session on a "drift bug" that was this:
    a test read 0.4 from an installed copy while the source beside it said
    0.20. Tonight it happened again -- a method added to `flow_math` was
    reported ABSENT by pytest while `grep` found it in the file.
  * ON THE PI -- `colcon build --symlink-install` COPIES rather than symlinks
    for this layout, so the install tree goes stale the moment source is
    edited, and the vehicle's suite validates code the vehicle is not running.
  * ANYWHERE -- a package deleted from source but still installed keeps
    passing its own tests.

The failure is always the same shape: the suite is green, and it is green
about the wrong file.

WHAT THIS DOES. `conftest.py` at the repo root is loaded by pytest before it
imports any test module, so it is early enough to fix `sys.path` for the whole
session. It puts every `src/<pkg>/` on the FRONT of the path and removes the
colcon `install/`+`build/` entries that would shadow them.

⚠ `duburi_interfaces` IS DELIBERATELY EXEMPT. Its Python is GENERATED by the
message compiler and exists only in the install tree -- there is no
`src/duburi_interfaces/duburi_interfaces/`. Purging its path would break
`from duburi_interfaces.msg import DuburiState` everywhere, so the rule is
"shadow only what we have source for", derived at run time rather than from a
hardcoded list that would rot the next time a package is added.
"""
import pathlib
import sys

_ROOT = pathlib.Path(__file__).resolve().parent
_SRC = _ROOT / 'src'


def _source_packages():
    """`src/<name>/<name>/` -- a real Python package, not a msg-only one."""
    if not _SRC.is_dir():
        return {}
    return {d.name: d for d in sorted(_SRC.iterdir())
            if d.is_dir() and (d / d.name).is_dir()}


def _install_shadow(entry: str, names) -> bool:
    """A colcon artefact for a package we have source for."""
    if '/install/' not in entry and '/build/' not in entry:
        return False
    return any(f'/{n}/' in entry for n in names)


def _pin_to_source():
    pkgs = _source_packages()
    if not pkgs:
        return []
    names = set(pkgs)

    # 1. Evict the shadows. Only ours, only where source exists.
    sys.path[:] = [p for p in sys.path if not _install_shadow(str(p), names)]

    # 2. Prepend our source dirs.
    for path in pkgs.values():
        entry = str(path)
        if entry in sys.path:
            sys.path.remove(entry)
        sys.path.insert(0, entry)

    # 3. Anything already imported from a shadow is still bound in
    #    sys.modules and would defeat both steps above. Drop those bindings so
    #    the next import re-resolves; harmless when nothing was imported yet.
    for mod in [m for m in list(sys.modules)
                if m.split('.')[0] in names]:
        installed = getattr(sys.modules[mod], '__file__', '') or ''
        if _install_shadow(installed, names):
            del sys.modules[mod]

    return list(pkgs)


PINNED = _pin_to_source()
