#!/usr/bin/env python3
"""Are the flare golf balls still ON their flares after the solver swap?

`sauvc_ball` is the only dynamic prop in the repo, so it is the only body whose
RESTING CONTACT is generated by the collision detector -- and that detector just
changed from `dart` to `bullet`. Sphere-on-cylinder-rim is exactly the pair
whose contact, friction and restitution defaults differ between the two.

VERIFY BY HEIGHT, NOT BY STABILITY. A ball lying on the pool floor is perfectly
stable; the check that asked "did z change" passed while all three were down.


    Usage, against a running sim:

        ros2 launch duburi_sim_bringup sim.launch.py course:=sauvc26_final \
            ardusub:=false bridge:=false gui:=false
        python3 ball_check.py

    Exits non-zero if any ball has left its cup, so it works as a gate.
    """
import os
import re
import subprocess
import sys
import time

WORLD = 'sauvc26_final'
HERE = os.path.dirname(os.path.abspath(__file__))
WORLD_FILE = os.path.join(HERE, '..', 'worlds', f'{WORLD}.world')
TOL = 0.05   # m below spawn height before we call it fallen

txt = open(WORLD_FILE).read()
expected = {m.group(1): float(m.group(2)) for m in re.finditer(
    r'<name>(\w+_ball)</name>\s*<pose>[-\d.e ]*?\s([-\d.e]+)\s+0 0 0</pose>', txt)}
if not expected:
    # pose is "x y z r p y"; take the third field.
    for m in re.finditer(r'<name>(\w+_ball)</name>\s*<pose>([^<]+)</pose>', txt):
        expected[m.group(1)] = float(m.group(2).split()[2])
if not expected:
    sys.exit('could not parse expected ball poses')

def pose_z(name):
    out = subprocess.run(['gz', 'model', '-m', name, '-p'],
                         capture_output=True, text=True, timeout=20).stdout
    m = re.search(r'\[([-\d.e]+)\s+([-\d.e]+)\s+([-\d.e]+)\]', out)
    return float(m.group(3)) if m else None

print(f'settling for 40 s of wall clock...')
time.sleep(40)

bad = []
for name, z0 in sorted(expected.items()):
    z = pose_z(name)
    if z is None:
        print(f'{name:20s} NOT FOUND'); bad.append(name); continue
    drop = z0 - z
    ok = drop < TOL
    print(f'{name:20s} spawn z={z0:+.3f}  now z={z:+.3f}  dropped {drop:+.3f} m'
          f'  {"OK" if ok else "FELL"}')
    if not ok:
        bad.append(name)
print()
print('RESULT: ' + ('all balls still on their flares'
                    if not bad else f'FELL: {bad}'))
sys.exit(1 if bad else 0)
