#!/usr/bin/env python3

"""Render every registered prop into a standalone model:// model.

Reads spec/arena.yaml, writes models/<prop>/model.sdf and model.config for each
entry in prop_library.PROPS. Worlds pull these in with <include>, and the GUI
resource panel and the runtime spawn service can both use them directly.

Usage:
    scripts/gen_props.py [--spec ...] [--outdir ...]
"""

import argparse
import os

import prop_library as pl

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DEFAULT_OUTDIR = os.path.join(PKG, "models")

MODEL_CONFIG = """<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>0.1.0</version>
  <sdf version="1.9">model.sdf</sdf>

  <author>
    <name>fh1m</name>
    <email>fh1m@users.noreply.github.com</email>
  </author>

  <description>
    SAUVC 2026 competition prop, generated by duburi_sim_worlds from
    spec/arena.yaml. Do not edit by hand; edit the spec and regenerate.
  </description>
</model>
"""

TEXTURES_CONFIG = """<?xml version="1.0"?>
<model>
  <name>sauvc_textures</name>
  <version>0.1.0</version>

  <author>
    <name>fh1m</name>
    <email>fh1m@users.noreply.github.com</email>
  </author>

  <description>
    Pool floor and wall textures, generated by scripts/gen_pool_texture.py.
    Exists as a model so that model://sauvc_textures/... URIs resolve; it has no
    geometry of its own.
  </description>
</model>
"""


def generate(spec_path: str, outdir: str, competition: str = None) -> None:
    """Bake every prop of one competition into models/<name>/model.sdf.

    Props are built against THEIR OWN competition's spec, not one global spec.
    That is the whole reason this is per-competition: depth-spanning props --
    the qualification gate, the orange flare -- read pool depth at build time
    and bake it in. SAUVC's pool is 1.6 m and RoboSub's is 2.1 m, so a single
    shared spec would silently generate one of them against the wrong pool.
    Model names already carry the competition prefix, so both sets coexist in
    one flat models/ directory without collision.
    """
    for name in sorted(pl.PROPS):
        comp = pl.prop_competition(name)
        if competition and comp != competition:
            continue
        spec = pl.load_spec(spec_path if competition else None, competition=comp)
        model_dir = os.path.join(outdir, name)
        os.makedirs(model_dir, exist_ok=True)

        with open(os.path.join(model_dir, "model.sdf"), "w") as f:
            f.write(pl.standalone_sdf(name, spec))
        with open(os.path.join(model_dir, "model.config"), "w") as f:
            f.write(MODEL_CONFIG.format(name=name))

        print(f"wrote {model_dir}/model.sdf")

    # Each competition's texture directory needs a model.config to resolve as a
    # model. One per competition because the floor/wall PNGs are sized from that
    # competition's pool.
    for comp in ([competition] if competition else pl.competitions()):
        tex_dir = os.path.join(outdir, pl.texture_model(comp))
        os.makedirs(tex_dir, exist_ok=True)
        with open(os.path.join(tex_dir, "model.config"), "w") as f:
            f.write(TEXTURES_CONFIG.replace("sauvc", comp))
        print(f"wrote {tex_dir}/model.config")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", default=None,
                        help="Arena spec YAML (overrides --competition).")
    parser.add_argument("--competition", default=None,
                        help="Only this competition (default: all).")
    parser.add_argument("--outdir", default=DEFAULT_OUTDIR, help="models/ directory.")
    args = parser.parse_args()

    generate(args.spec, args.outdir, args.competition)


if __name__ == "__main__":
    main()
