#!/usr/bin/env python3

"""Render every registered prop into a standalone model:// model.

Reads spec/arena.yaml, writes models/<prop>/model.sdf and model.config for each
entry in prop_library.PROPS. Worlds pull these in with <include>, and the GUI
resource panel and the runtime spawn service can both use them directly.

Usage:
    scripts/gen_props.py [--spec ...] [--outdir ...]
"""

import argparse
import os

import prop_library as pl

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DEFAULT_OUTDIR = os.path.join(PKG, "models")

MODEL_CONFIG = """<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>0.1.0</version>
  <sdf version="1.9">model.sdf</sdf>

  <author>
    <name>fh1m</name>
    <email>fh1m@users.noreply.github.com</email>
  </author>

  <description>
    SAUVC 2026 competition prop, generated by duburi_sim_worlds from
    spec/arena.yaml. Do not edit by hand; edit the spec and regenerate.
  </description>
</model>
"""

TEXTURES_CONFIG = """<?xml version="1.0"?>
<model>
  <name>sauvc_textures</name>
  <version>0.1.0</version>

  <author>
    <name>fh1m</name>
    <email>fh1m@users.noreply.github.com</email>
  </author>

  <description>
    Pool floor and wall textures, generated by scripts/gen_pool_texture.py.
    Exists as a model so that model://sauvc_textures/... URIs resolve; it has no
    geometry of its own.
  </description>
</model>
"""


def generate(spec_path: str, outdir: str) -> None:
    spec = pl.load_spec(spec_path)

    for name in sorted(pl.PROPS):
        model_dir = os.path.join(outdir, name)
        os.makedirs(model_dir, exist_ok=True)

        with open(os.path.join(model_dir, "model.sdf"), "w") as f:
            f.write(pl.standalone_sdf(name, spec))
        with open(os.path.join(model_dir, "model.config"), "w") as f:
            f.write(MODEL_CONFIG.format(name=name))

        print(f"wrote {model_dir}/model.sdf")

    # The texture directory needs a model.config to be resolvable as a model.
    tex_dir = os.path.join(outdir, pl.TEXTURE_MODEL)
    os.makedirs(tex_dir, exist_ok=True)
    with open(os.path.join(tex_dir, "model.config"), "w") as f:
        f.write(TEXTURES_CONFIG)
    print(f"wrote {tex_dir}/model.config")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", default=pl.DEFAULT_SPEC, help="Arena spec YAML.")
    parser.add_argument("--outdir", default=DEFAULT_OUTDIR, help="models/ directory.")
    args = parser.parse_args()

    generate(args.spec, args.outdir)


if __name__ == "__main__":
    main()
