"""Let the unit tests run without a built ROS workspace.

`mongla_interfaces` is generated by colcon from the .msg/.action files, so it only
exists after a build inside a sourced ROS environment. Every test module here
transitively imports it (`mongla_control/__init__.py` pulls in `mongla.py`, which
imports `Move`), so the whole suite could only be COLLECTED on a machine with ROS 2
installed -- including the tests that exercise nothing but arithmetic.

When the real package is importable this file does nothing at all.

When it is not, a stand-in is built **by parsing the .action / .msg files in this
repo**. Parsing rather than hardcoding is deliberate: `Move.action` grows fields
regularly (`surge_sign`, the depth bounds, `err_x_px`...), and a hardcoded field
list silently diverges -- `test_every_field_is_on_move_goal` exists precisely to
catch a `COMMANDS` row naming a field the action does not have, and it cannot do
that job against a stale fake. Parsed, the stub is correct by construction.

This is a test-collection convenience, not a substitute for building the workspace:
anything depending on real message serialisation, on rclpy, or on the action
machinery still needs a proper ROS run.
"""

import re
import sys
import types
from pathlib import Path

# mongla_control/test/conftest.py -> src/
_SRC = Path(__file__).resolve().parents[2]
_IFACE = _SRC / 'mongla_interfaces'

# rosidl primitive -> (python default, the type string
# get_fields_and_field_types() reports). Only the primitives these interfaces use.
_TYPES = {
    'bool':    (False, 'boolean'),
    'string':  ('',    'string'),
    'float32': (0.0,   'float'),
    'float64': (0.0,   'double'),
    'int8':    (0,     'octet'),
    'int16':   (0,     'int16'),
    'int32':   (0,     'int32'),
    'uint8':   (0,     'uint8'),
    'uint32':  (0,     'uint32'),
}

_FIELD_RE = re.compile(r'^\s*([A-Za-z0-9_/]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:#.*)?$')


def _parse_block(lines):
    """rosidl field lines -> {name: (default, type_string)}."""
    out = {}
    for line in lines:
        line = line.split('#', 1)[0].rstrip()
        if not line.strip():
            continue
        m = _FIELD_RE.match(line)
        if not m:
            continue
        rostype, name = m.group(1), m.group(2)
        out[name] = _TYPES.get(rostype, (None, rostype))   # e.g. std_msgs/Header
    return out


def _make(name, fields):
    def __init__(self):
        for key, (default, _t) in fields.items():
            setattr(self, key, default)

    # rosidl generates this on every message class; `test_every_field_is_on_move_goal`
    # uses it to assert the COMMANDS registry cannot name a field the action lacks.
    @classmethod
    def get_fields_and_field_types(cls):
        return {k: t for k, (_d, t) in fields.items()}

    return type(name, (), {
        '__init__': __init__,
        '_fields': tuple(fields),
        'get_fields_and_field_types': get_fields_and_field_types,
    })


def _split_sections(text):
    """Goal / Result / Feedback. Splits on lines that are EXACTLY `---`.

    Not `text.split('---')`: Move.action uses `---` as a horizontal rule inside its
    comment blocks 12 times, so a substring split truncates Goal at the first one and
    silently loses every field after it (`flips`, `headroom`, all the vision fields).
    Comments are stripped first so a rule inside one can never be mistaken for a
    section separator.
    """
    sections, cur = [], []
    for line in text.splitlines():
        body = line.split('#', 1)[0].strip()
        if body == '---':
            sections.append(cur)
            cur = []
        else:
            cur.append(line)
    sections.append(cur)
    while len(sections) < 3:
        sections.append([])
    return sections[:3]


def _install_stub():
    action = (_IFACE / 'action' / 'Move.action').read_text(encoding='utf-8')
    goal, result, feedback = (_parse_block(s) for s in _split_sections(action))

    move = type('Move', (), {})
    move.Goal = _make('Goal', goal)
    move.Result = _make('Result', result)
    move.Feedback = _make('Feedback', feedback)

    state_src = (_IFACE / 'msg' / 'MonglaState.msg').read_text(encoding='utf-8')
    state = _make('MonglaState', _parse_block(state_src.splitlines()))

    pkg = types.ModuleType('mongla_interfaces')
    mod_action = types.ModuleType('mongla_interfaces.action')
    mod_msg = types.ModuleType('mongla_interfaces.msg')
    mod_action.Move = move
    mod_msg.MonglaState = state
    pkg.action, pkg.msg = mod_action, mod_msg

    sys.modules.setdefault('mongla_interfaces', pkg)
    sys.modules.setdefault('mongla_interfaces.action', mod_action)
    sys.modules.setdefault('mongla_interfaces.msg', mod_msg)


try:
    import mongla_interfaces.action  # noqa: F401
except ImportError:
    _install_stub()
