#!/usr/bin/env bash
# Regenerate the standalone simulator mirror from mongla_ws/sim/.
#
#   mongla_ws/sim/   CANONICAL -- land every change here
#   fh1m/mongla-sim_ws   MIRROR -- generated by this script, for sim-only work
#
# Two copies of a tree drift unless one of them is generated. This makes the
# mirror generated: it is sourced from `git ls-files sim/`, so ONLY tracked files
# can reach it. That is deliberate rather than a `cp -a` -- the sim's own
# .gitignore does not list `*.pt`, `.remember/` or `logs/`, which are covered by
# mongla_ws's ROOT ignore file and would stop applying the moment the tree stood
# alone. Sourcing from the index means the mirror cannot pick up a model weight or
# a 669 MB log directory no matter what is lying around on disk.
#
#   tools/sync_sim_mirror.sh [target-dir]        default: ../mongla-sim_ws
#
# Review the diff, then commit and push from the target. This script never
# commits and never pushes.
set -euo pipefail

WS="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-$(cd "$WS/.." && pwd)/mongla-sim_ws}"
UPSTREAM="https://github.com/fh1m/mongla_ws"

cd "$WS"
[ -d sim/src ] || { echo "error: no sim/src under $WS" >&2; exit 1; }

if [ -n "$(git status --porcelain sim/)" ]; then
    echo "error: sim/ has uncommitted changes -- the mirror is built from the git" >&2
    echo "       index, so it would silently ship the committed version instead." >&2
    git status --short sim/ >&2
    exit 1
fi

mkdir -p "$TARGET"
# Replace only what we generate; leave the target's .git and any local build/
# datasets alone so a working checkout is not destroyed by a re-sync.
rm -rf "$TARGET/src" "$TARGET/scripts" "$TARGET/.context"

git ls-files -z sim/ | while IFS= read -r -d '' f; do
    rel="${f#sim/}"
    mkdir -p "$TARGET/$(dirname "$rel")"
    cp -p "$f" "$TARGET/$rel"
done

# COLCON_IGNORE exists to keep mongla_ws's ROOT build at six packages. Standalone
# there is no root build to protect, and leaving it means `colcon build` in the
# mirror silently builds nothing.
rm -f "$TARGET/COLCON_IGNORE"

# Links that point out of sim/ resolve inside mongla_ws but dangle in the mirror.
# Send them to the upstream repo instead of leaving 404s.
python3 - "$TARGET" "$UPSTREAM" <<'PY'
import pathlib, re, sys
target, upstream = pathlib.Path(sys.argv[1]), sys.argv[2]
blob = f'{upstream}/blob/main'
for md in target.rglob('*.md'):
    s0 = s = md.read_text()
    depth = len(md.relative_to(target).parts) - 1      # how many ../ mean "leave sim/"
    def fix(m):
        text, href = m.group(1), m.group(2)
        ups = len(re.findall(r'\.\./', href))
        if ups <= depth:                                # still inside the mirror
            return m.group(0)
        return f'[{text}]({blob}/{href.lstrip("./").replace("../", "")})'
    s = re.sub(r'\[([^\]]*)\]\((\.\./[^)]*)\)', fix, s)
    if s != s0:
        md.write_text(s)
PY

README="$TARGET/README.md"
if ! grep -q '<!-- MIRROR -->' "$README"; then
    printf '%s\n' "$(cat <<EOF
<!-- MIRROR -->
> **This repository is a generated mirror.**
> The simulator is developed inside the autonomy repo at
> [\`mongla_ws/sim/\`]($UPSTREAM/tree/main/sim), which is canonical. This copy is
> regenerated by \`tools/sync_sim_mirror.sh\` for sim-only work. **Open pull
> requests against [$UPSTREAM]($UPSTREAM)** — changes committed here are
> overwritten by the next sync.
>
> **Do not build this on a machine that also builds \`mongla_ws/sim\`,** or
> never source both overlays. \`ros2 run mongla_sim_bringup ...\` resolves by
> \`AMENT_PREFIX_PATH\` order, so with two installed copies you can end up
> running mirror code while editing the canonical tree — and nothing says so.

$(cat "$README")
EOF
)" > "$README"
fi

echo "mirror written to $TARGET"
echo "review, then:  cd $TARGET && git add -A && git commit && git push"
